### ISSUE TITLE
Launch this program on your Computer?

### ISSUE THREAD

**Issue by ps4gentoo** [charlyzard/PS4OfflineAccountActivator#1]
how?..Visual Studio ? what i need?

greez

**Comment by ps4gentoo** [comment]
is not working for me;( can u pls help

i get a  error on this position
private CMD_STATUS ReceiveStatus()
        {
            byte[] status = new byte[4];
            sock.Receive(status, 4, SocketFlags.None);
            return (CMD_STATUS)BitConverter.ToUInt32(status, 0);
        }

**Comment by charlyzard** [comment]
Are you using ps4debug version 1.5? Did you change the code to point to your PS4's IP address?
Post a screenshot of the error and I'll try to help.

**Comment by ps4gentoo** [comment]
thx for help, no used version 1.1. now with version 1.5 works
executable base 497C0000
