### ISSUE TITLE
Update for 6.72

### ISSUE THREAD

**Issue by krugdenis** [charlyzard/PS4OfflineAccountActivator#5]
https://github.com/GiantPluto/ps4debug
is making ps4debug for 6.72 FW.
I've tried to compile with it, but we need offsets for 5.05 in your project.
Very appreciate your work!

**Comment by charlyzard** [comment]
I updated the offsets, but you'll need an updated ps4debug for 6.72. Please try with the version you linked and report if it's working.

**Comment by GiantPluto** [comment]
I have ported both ps4debug and offline activator. Here is the link to [ps4debug ](https://github.com/GiantPluto/ps4debug) and offline [activator ](https://github.com/GiantPluto/PS4OfflineAccountActivator) if you want. One of the guys in Day0 discord has tested and verified that the activator works.

**Comment by krugdenis** [comment]
@charlyzard @GiantPluto I've tested both of your works! Excellent work! Thank you!

**Comment by lollipop6969** [comment]
@GiantPluto where can i download your new ps4debug.bin? on the release page is no new entry.

**Comment by krugdenis** [comment]
> @GiantPluto where can i download your new ps4debug.bin? on the release page is no new entry.

you can compile it on Ubuntu from source, or search twitter and discord channels

**Comment by lollipop6969** [comment]
@krugdenis
can you please give me the ps4debug.bin. i have no idea of these things. very appreciated.

**Comment by GiantPluto** [comment]
You can take the binaries from https://github.com/GiantPluto/ps4debug/releases/tag/v1.0
