### ISSUE TITLE
please update to 6.72

### ISSUE THREAD

**Issue by lollipop6969** [charlyzard/PS4OfflineAccountActivator#6]
good morning sir.
please update offline account activator to 6.72 so that we can offline- and id-activate accounts to import 5.05 savegames.
thats very important for people like me who have 5.05 usb savegames from back in the day and now have bought a 6.72 ps4.
would be very very appreciated. i have a 1000h+ diablo savegame and cant do anything with it.

**Comment by charlyzard** [comment]
I updated the offsets, but you'll need an updated ps4debug for 6.72.

**Comment by GiantPluto** [comment]
Use the ps4debug from https://github.com/GiantPluto/ps4debug/releases/tag/v1.0

**Comment by lollipop6969** [comment]
@charlyzard @GiantPluto i was able to import my 1000h+ diablo savegame which contains insane amounts of gold, gems, ultra rare items, materials, builds, etc etc. i thought my acc was lost forever. but now i can play diablo rifts again. you guys are amazing. you didnt cure cancer but you guys are still lil heroes for our community. thank you so so much.
