### ISSUE TITLE
strange error after updating for some people 

### ISSUE THREAD

**Issue by lollipop6969** [charlyzard/PS4OfflineAccountActivator#8]
good morning sir.
would you kindly check this thread and maybe help or clarify or update?

https://twitter.com/hyndrid/status/1292520816475873280?s=19

kind regards

**Comment by lollipop6969** [comment]
https://twitter.com/hyndrid/status/1292632367446798336?s=19

**Comment by charlyzard** [comment]
That error means SCE_NP_TROPHY_ERROR_IMAGE_FILE_CORRUPTED.

As I said in the readme it's recommended to delete the trophy folder, but people don't read it...
