### ISSUE TITLE
offline account activator 7.02 

### ISSUE THREAD

**Issue by lollipop6969** [charlyzard/PS4OfflineAccountActivator#9]
good morning sir, would you kindly update offline account activator to 7.02?

**Comment by pokechar** [comment]
PS4debug for version 7.02 is here:

https://github.com/Nazky/PS4Debug

I compiled it and work for 7.02.
Only need to have PS4 Offline Account Activator for version 7.02

**Comment by fredyfartas** [comment]
I have the same problem, I hope the program is updated soon so I can use it in 7.02

**Comment by fredyfartas** [comment]
My intention is not to be heavy, just to know if I know how the subject is going, if it is likely that they will update it or I already lose hope

**Comment by SiliPSX** [comment]
Give it a try and report if its working:
https://github.com/SiliPSX/PS4OfflineAccountActivator.git

**Comment by fredyfartas** [comment]
I have downloaded the files but there is no executable

**Comment by SiliPSX** [comment]
Build it with Visual Studio.

**Comment by fredyfartas** [comment]
ok, thanks, I'll try to do it

**Comment by fredyfartas** [comment]
I have not been able to do it, since I am new to this, anyway thanks for your time and work.
in the end I got it, I needed to add the ps4debug libraries, and it has worked perfectly, I already have my account activated

**Comment by fredyfartas** [comment]
the activation of the account seems correct, however I receive an error when copying the games, both from a usb to the system disk and vice versa

**Comment by bradman117** [comment]
I'm very interested in this! Hopefully everything will work in the near future!

**Comment by bradman117** [comment]
Yeah there is a problem with sending or receiving, CE 33116-4

**Comment by fredyfartas** [comment]
Yes, it is the same error that I have, I hope it can be solved

**Comment by lollipop6969** [comment]
@charlyzard please port to 7.02!

**Comment by pokechar** [comment]
New version:
https://github.com/Joonie86/PS4OfflineAccountActivator/releases/tag/v1.1_for_7.02

**Comment by SiliPSX** [comment]
So i just had the getInt and setStr Offset wrong...

**Comment by pokechar** [comment]
It works fine, you have to use the payload "ps4debug.bin" that is included in the .zip file

**Comment by fredyfartas** [comment]
the account activates it, but it won't let me copy the games, yes, with a new user and activating it with the id of my games, thanks for your great work

**Comment by fredyfartas** [comment]
thanks for your great work, it worked well for me and I can now copy the games without problems

**Comment by hippie68** [comment]
Guys, the ps4debug.bin doesn't work on my 7.02 PS4 Slim. Instant power down each time the payload is sent. I would complain about this on Joonie86's repository, but he disabled Issues. So it seems we need more work on ps4debug.bin to make it compatible for all PS4 versions.

**Comment by fredyfartas** [comment]
I am in 7.02 and my ps4 is slim, it has worked for me without problems, using the debug of the ps4 hosts
